# Data
data.datatype: "example"
data.root: ""
data.img_h: ""
data.img_w: ""

# Train
train.per_gpu_batch_size: 2
train.num_workers: 4
train.epochs: 100
train.log_freq: 10
train.vis_freq: 200
train.save_freq: 2000
train.eval_freq: 5000

train.learning_rate: 0.001
train.pretrained_checkpoint_path: null